services:
  aksara-nuxt:
    build:
      context: .
      args:
        NUXT_PUBLIC_API_BASE_URL: ${NUXT_PUBLIC_API_BASE_URL}
        NUXT_PUBLIC_EXTERNAL_API_URL: ${NUXT_PUBLIC_EXTERNAL_API_URL}
        NUXT_PUBLIC_EMBED_API_URL: ${NUXT_PUBLIC_EMBED_API_URL}
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - web-gateway

networks:
  web-gateway:
    external: true
